language: node_js
sudo: false
cache: yarn
node_js: 11
script: yarn lint && yarn lint:css && yarn test:ci && yarn build
deploy:
  provider: heroku
  api_key:
    secure:
  app:
    master: js-books-staging
